### PR TITLE
Added support for new/update/cancel position channels

### PR DESCRIPTION
**Pull request by eSanity**
Ran into an issue where pu/pn/pc gave 'Channel ID does not have data handler', found out it was not implemented yet. It is a trivial enough addition that I thought it might make sense to immediately deploy it to the release but I am not sure what your workflow is yet, so I made the changes to the dev branch.

### CODE REVIEW

**Comment by eSanity** [comment]
After some more reading it seems like there are more deprecated functions ("Historical Orders", "HIstorical Offers", "Historical Credits", "Historical Loans") that are still in the code that have to be replaced with their 'xn' 'xu' 'xc' equivalents.

**Comment by nlsdfnbch** [comment]
Yes,  that's probably a better approach. I'm working on a different solution atm because the way the client currently works isn't feasible (eats too much memory and is really unwieldy).  Do you want to implement the single-queue change? If so,  open a new PR for that. 

My work flow is as close as I can be bothered(it is a hobby project, afterall) to nvie.com's "successful git branching model" - have a look at that if you're interested.

**Comment by eSanity** [comment]
I could implement it, yeah. However, wouldn't the most elegant solution be to bunch all the account stuff into one queue? Do away with the translation table, add `_handle_account` to the `_data_handlers`. It automatically means that if you want to get updates for your account data that you empty out the rest of the account queue as well. Which if you care about queues slowly filling up means you do not have keep a list of 20 queues on your own end and going through them. That'd be more than just a hotfix, though. 

The new client is the ZMQ project, right?

**Comment by nlsdfnbch** [comment]
Yes, the single queue would be more than a hotfix - which is why I suggested a new PR for that. The current PR would be a hotfix. Sorry if that wasn't clear. 

And yes, that's the ZMQ branch. It's just easier, more stable and faster with zmq. Just thinking about all those `Lock.acquire()` calls in the current implementation makes me dizzy.

**Pull request merged**
